### ISSUE TITLE
Listing and defining forbidden paths

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-urlaliases#2]
Field regex: 
- no spaces or special characters
- simple urls only (no more than one slash --> [domain]/alias) ? 
// not sure on this one @moustachu 

Forbidden values: 
- admin
- system
- user
- pages
- faq

- processes
- assemblies
- initiatives
- consultations
- conferences
- search
- conversations
- notifications
- account
- notifications_settings
- authorizations
- own_user_groups
- user_interests
- data_portability

All of the above +
- ?locale=fr 
- ?locale=en
- and so on for all existing languages

**Comment by aitorlb** [comment]
I agree with @moustachu that it is much simpler to just allow simple slugs.

We have been able to extract all the listed reserved paths dinamically, so it won't have to be updated manually if something changes: [reserved_paths.txt](https://github.com/OpenSourcePolitics/decidim-urlaliases/files/3550518/reserved_paths.txt)

As for the locales, we won't have to worry if "**?**" is considered a special character. But we should agree which are the special characters, because right now in the application we made it like this:

> Only accepts letters, numbers, dashes, underscores and must start with a "/".

**Comment by virgile-dev** [comment]
I'm good with considering "?" as special character. It solves the language issue quite simply I like it.
Great you could extract the reserved path dynamically. Onwards 🚀
